version: '3.8'

services:
    springboot-app:
        build: .
        container_name: springboot-container
        ports:
            - "8080:8080"
        environment:
            SPRING_PROFILES_ACTIVE: dev
        networks:
            - spring-network

networks:
    spring-network:
