version: '3.8'

services:
    springboot-app:
        build: .
        container_name: backend
        ports:
            - "8080:8080"
        networks:
            - dokploy-network

networks:
    dokploy-network:
