spring:
    application:
        name: workflow
    datasource:
        url: jdbc:h2:mem:testdb;DATABASE_TO_UPPER=false
        username: workflow
        password: password
        driverClassName: org.h2.Driver
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        defer-datasource-initialization: true
        hibernate:
            ddl-auto: create-drop
    h2:
        console:
            enabled: true
    pebble:
        suffix: ".html"
        cache: false
        enabled: true
        encoding: UTF-8
    mustache:
        suffix: .html
        cache: false
        prefix: classpath:/templates/
        enabled: false
    devtools:
        livereload:
            enabled: true
            # additional-paths: .
        restart:
            enabled: true
            # additional-paths: .
            # poll-interval: 2s
            # quiet-period: 1s
    main:
        log-startup-info: false
        lazy-initialization: true
    # resources:
    #     add-mappings: false
    #     static-locations: classpath:/resources/templates
    #     cache:
    #         period: 0
server:
    error:
        include-message: always
        include-stacktrace: NEVER
    servlet:
        path-matching:
            use-trailing-slash-match: true

hibernate:
    id:
        new_generator_mappings: true

management:
    endpoints:
        web:
            exposure:
                include: mappings
