spring.application.name=workflow
server.port=8080
#spring.datasource.url=jdbc:postgresql://localhost:32768/mydatabase?useUnicode=true&characterEncoding=utf-8
#spring.datasource.username=myuser
#spring.datasource.password=secret
#spring.datasource.url=jdbc:h2:mem:testdb;DATABASE_TO_UPPER=false
#spring.datasource.driverClassName=org.h2.Driver
# spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.defer-datasource-initialization=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.datasource.initialization-mode=always
spring.sql.init.mode=always
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.connection.autocommit=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.connection.charSet=UTF-8
spring.jpa.properties.hibernate.hbm2ddl.import_files_sql_extractor=org.hibernate.tool.schema.internal.script.MultiLineSqlScriptExtractor
spring.datasource.data=classpath:/data.sql

# spring.h2.console.enabled=true
pebble.suffix=.html
pebble.cache=false
pebble.enabled=true
pebble.encoding=UTF-8
#spring.pebble.prefix=classpath:/templates/
#spring.mustache.suffix=.html
#spring.mustache.cache=false
#spring.mustache.prefix=classpath:/templates/
#spring.mustache.enabled=false
spring.devtools.livereload.enabled=true
# additional-paths: .
spring.devtools.restart.enabled=true
# additional-paths: .
# poll-interval: 2s
# quiet-period: 1s
spring.main.log-startup-info=false
spring.main.lazy-initialization=true
# resources:
#     add-mappings: false
#     static-locations: classpath:/resources/templates
#     cache:
#         period: 0
server.error.include-message=always
server.error.include-stacktrace=NEVER
server.compression.enabled=true
server.compression.min-response-size=2048
server.compression.mime-types=application/json,application/xml,text/html,text/xml,text/plain
servlet.path-matching.use-trailing-slash-match=true

hibernate.id.new_generator_mappings=true
management.endpoints.web.exposure.include=mappings
management.endpoint.restart.enabled=true

security.jwt.secret-key=3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
# 1h in millisecond
security.jwt.expiration-time=3600000
