spring:
    config:
        import: optional:file:.env[.properties]
    application:
        name: headknot
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB}"
        username: ${POSTGRES_USERNAME}
        password: ${POSTGRES_PASSWORD}
#        url: jdbc:postgresql://headknot-database-7c9pzr:5432/headknot_db
#        username: admin
#        password: admin
        initialization-mode: always
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                connection:
                    autocommit: false
                    charSet: UTF-8
                format_sql: true
        defer-datasource-initialization: true
    sql:
        init:
            mode: always
    devtools:
        livereload:
            enabled: true
        restart:
            enabled: true
    main:
        log-startup-info: false
        lazy-initialization: true

server:
    port: ${SPRING_PORT:8080}
    error:
        include-message: always
        include-stacktrace: never
    compression:
        enabled: true
        min-response-size: 2048
        mime-types: application/json,application/xml,text/html,text/xml,text/plain
    servlet:
        path-matching:
            use-trailing-slash-match: true

management:
    endpoints:
        web:
            exposure:
                include: mappings
    endpoint:
        restart:
            enabled: true

hibernate:
    id:
        new_generator_mappings: true
